[workspace.package]
license = "Apache-2.0"
authors = ["rust-evm Developers <contact-rust-evm@pacna.org>"]
repository = "https://github.com/rust-ethereum/evm"
keywords = ["no_std", "ethereum", "evm"]

[package]
name = "evm"
version = "1.0.0-dev"
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
description = "Ethereum Virtual Machine"
edition = "2018"

[dependencies]
auto_impl = "1.0"
ethereum = { version = "0.14", default-features = false }
log = { version = "0.4", default-features = false }
primitive-types = { version = "0.12", default-features = false, features = ["rlp"] }
rlp = { version = "0.5", default-features = false }
sha3 = { version = "0.10", default-features = false }

# Optional dependencies
environmental = { version = "1.1.2", default-features = false, optional = true }
scale-codec = { package = "parity-scale-codec", version = "3.2", default-features = false, features = ["derive"], optional = true }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

evm-interpreter = { version = "1.0.0-dev", path = "interpreter", default-features = false }

[dev-dependencies]
criterion = "0.4"
hex = "0.4"

[features]
default = ["std"]
std = [
	"ethereum/std",
	"log/std",
	"primitive-types/std",
	"rlp/std",
	"sha3/std",
	"environmental/std",
	"scale-codec/std",
	"scale-info/std",
	"serde/std",
	"evm-interpreter/std",
]
with-codec = [
	"scale-codec",
	"scale-info",
	"primitive-types/codec",
	"primitive-types/scale-info",
	"ethereum/with-codec",
	"evm-interpreter/with-codec",
]
with-serde = [
	"serde",
	"primitive-types/impl-serde",
	"evm-interpreter/with-serde",
	"ethereum/with-serde",
]

[workspace]
members = [
	"interpreter",
	"jsontests",
	"precompile",
	"tracer",
]
