[package]
name = "evm-gasometer"
version = "0.40.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>", "Parity Technologies <admin@parity.io>"]
description = "Portable Ethereum Virtual Machine implementation written in pure Rust."
repository = "https://github.com/sorpaas/rust-evm"
keywords = ["no_std", "ethereum"]
edition = "2018"

[dependencies]
primitive-types = { version = "0.12", default-features = false }

evm-interpreter = { version = "0.2.0-dev", path = "../interpreter", default-features = false }

[features]
default = ["std"]
std = [
	"primitive-types/std",
	"evm-interpreter/std",
]
