[package]
name = "evm-tracer"
version = "0.0.0-dev"
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
edition = "2021"

[dependencies]
evm = { path = ".." }
